### ISSUE TITLE
Availability of Graph Node Editor

### ISSUE THREAD

**Issue by jostlowe** [setzer22/blackjack#10] opened 2022-02-01 11:50 UTC
Hi!

Wow, this project looks really cool! Great work

I've been on the lookout for a graph node editor, similar to the one implemented in this project. It is intended for a server routing network traffic for stage lighting protocols. 

Is there any way of re-using the graph editor from this project? Is there any chance that the graph editor might be separated into its own crate in the future?

**Comment by jam1garner** [comment] 2022-02-04 21:25
It seems the author [expressed interest](https://www.reddit.com/r/rust_gamedev/comments/rufvlc/-/hr1xe39), which is great because the mode editor seems really well done!

**Comment by ThePuzzlemaker** [comment] 2022-02-05 00:48
I'd really like to see this for a project I'm working on, so do let me know if/when this will be done :P

**Comment by setzer22** [comment] 2022-02-05 10:25
Hey all! Yes, this is indeed something I'd intend to work on at some point :)

 Right now there are two main roadblocks that make it a bit difficult:

- Zooming of UIs is not supported by egui AFAIK and for blackjack required a very specific setup with the wgpu backend. This could be replicated on other back-ends, but this part of the code is not portable.

- I'm still haven't had time to figure out a good API for this independent graph crate. It should have the ability to define node types as well as the data types that can flow through the graph, potentially with each data type having a widget function so it can be rendered inline with the node.

For the zoom issue, I think to make this portable a solution must be considered at the egui level, but I'm not sure how difficult would that be, or if the author would be interested in a feature like this. On the other hand, the other roadblock looks very easy to tackle, and it's just that I haven't had time to put some serious thought into this yet. So I think a good plan would be to offer the node graph as an independent crate without the ability to zoom for the time being, but with enough parameters to allow other people to implement zooming in their backend, should they want to do it.

**Comment by francesco-cattoglio** [comment] 2022-02-05 13:38
The interest in this is very high. I have started studying Blackjack's editor code and hopefully I will be able to contribute to this project sooner than later.

**Comment by ThePuzzlemaker** [comment] 2022-02-10 00:42
> Zooming of UIs is not supported by egui AFAIK and for blackjack required a very specific setup with the wgpu backend. This could be replicated on other back-ends, but this part of the code is not portable.
@setzer22 I was able to get (the concept of) zoom to work (though it didn't look nice) with just pure egui (w/ glium). It may not be the best solution, but you can basically just do `ui.input().scroll_delta.y` (or `zoom_delta` if you want it to use ctrl+scroll not scroll)

**Comment by setzer22** [comment] 2022-02-10 08:44
Hi @ThePuzzlemaker! Detecting *when* I should zoom (i.e. `zoom_delta`) is already very portable. The problem is zooming an arbitrary child `ui` whithin an egui application. This would involve a mechanism to create a `child_ui` so that it gets a larger `available_size` and `pixels_per_point` values, which are then automatically shrunk by egui to fit the original available size.

I'm quite happy with the current implementation, but it basically requires two separate egui instances and very fine-grained control about how input events are forwarded to the child instance.

**Comment by ThePuzzlemaker** [comment] 2022-02-11 00:30
Oh wait--that's how you do zoom :thinking: I thought you just used the zoom factor to do some type of scaling when drawing nodes and connections

**Comment by setzer22** [comment] 2022-02-11 09:36
Yup! The problem with doing scaling like that is that the widgets would not get larger. I could figure out a way to shrink the widgets by playing around with `spacing` and proportionally scaling fonts. But the way I'm currently doing zoom is guaranteed to work no matter what you draw, so it feels conceptually cleaner

**Comment by setzer22** [comment] 2022-02-19 18:54
The graph node editor behind blackjack is now [its own crate](https://github.com/setzer22/egui_node_graph)!

**Comment by setzer22** [comment] 2022-03-08 20:32
Closing, since this was implemented as part of #18

**Closed by setzer22** 2022-03-08 20:32 UTC
